### ISSUE TITLE
Open savefile and nothing happens

### ISSUE THREAD

**Issue by crykah** [Synthlight/Nexomon-Extinction-Save-Editor#9]
Faulting application name: Save-Editor.exe, version: 1.6.0.0, time stamp: 0x6243f19c
Faulting module name: KERNELBASE.dll, version: 10.0.22543.1000, time stamp: 0x79a69917
Exception code: 0xe0434352
Fault offset: 0x000000000001228c
Faulting process id: 0x0x3EA4
Faulting application start time: 0x0x1D884DE7C18C9FC
Faulting application path: C:\Users\tomkr\Downloads\Nexomon-Extinction-Save-Editor-1.6\Nexomon-Extinction-Save-Editor-1.6\Save-Editor.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: f181e878-ab41-4be2-824c-ad680ea1ace1
Faulting package full name: 
Faulting package-relative application ID:

```
Application: Save-Editor.exe
CoreCLR Version: 4.700.22.26002
.NET Core Version: 3.1.26
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Save_Editor.MainWindow' that matches the specified binding constraints threw an exception.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt16()
   at Save_Editor.Models.Extensions.ReadMonster(BinaryReader reader, Int32 saveVersion) in R:\Games\Nexomon Extinction\Save-Editor\Models\Monster.cs:line 34
   at Save_Editor.Models.SaveData..ctor(BinaryReader reader, Boolean readPs4PrefixBytes, Nullable`1 saveSize) in R:\Games\Nexomon Extinction\Save-Editor\Models\SaveData.cs:line 86
   at Save_Editor.Models.Ps4.Ps4Header..ctor(BinaryReader reader) in R:\Games\Nexomon Extinction\Save-Editor\Models\Ps4\Ps4Header.cs:line 28
   at Save_Editor.MainWindow.LoadFile() in R:\Games\Nexomon Extinction\Save-Editor\MainWindow.xaml.cs:line 63
   at Save_Editor.MainWindow..ctor() in R:\Games\Nexomon Extinction\Save-Editor\MainWindow.xaml.cs:line 28
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Save_Editor.App.Main()
```

**Comment by Synthlight** [comment]
And the save with which to reproduce the error?

**Comment by Synthlight** [comment]
Can't do anything without the save.
